# Generated by Django 5.0.2 on 2024-03-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desciption',
            new_name='description',
        ),
    ]
