# Generated by Django 5.0.2 on 2024-03-31 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_desciption_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
