# Generated by Django 5.0.2 on 2024-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
